### ISSUE TITLE
error when including in my package.json

### ISSUE THREAD

**Issue by andreujuanc** [dougludlow/ng2-bs3-modal#23]
Hello,

Im using VS2015, and wanted to add it from npm, so adding "ng2-bs3-modal": "0.4.2" to my package.json gave the folowing error:

`npm WARN peerDependencies The peer dependency angular2@2.0.0-beta.9 included from ng2-bs3-modal will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency bootstrap@3.3 included from ng2-bs3-modal will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\andre\Documents\Visual Studio 2015\Projects\Angular2Testing\Angular2Testing\src\Shoppius\npm-debug.log`

I have no idea what can i do. 

I can install any other packages without problem. Including angular, bootstrap and others.

Thanks!

**Comment by d1820** [comment]
That means you need to add the angular.beta.9 dependency your self before you try and add this package

**Comment by andreujuanc** [comment]
Im using angular beta11, do I have to downgrade?

**Comment by dougludlow** [comment]
@andreujuanc unfortunately, yes. ng2-bs3-modal is not compatible with versions later than beta.9 do to a current issue: https://github.com/angular/angular/issues/7671. 

Aside from using beta.9, I haven't had a chance to find a suitable workaround just yet.

**Comment by dougludlow** [comment]
@andreujuanc It appears the the above issue is resolved. I just tested it and the ng2-bs3-modal appears to be compatible with beta.12. Try v0.4.3.

**Comment by andreujuanc** [comment]
I still cant get it. Updated to angular beta 12 without problems, added modal and got this:

> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v0.12.2
> npm ERR! npm  v2.7.4
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported
> npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.8
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  any
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: ia32

**Comment by dougludlow** [comment]
This was due to me shrinkwrapping the project. Try installing v0.4.4 and let me know how it goes.

**Comment by andreujuanc** [comment]
I can confirm version 0.4.4 is working with angular beta 12.

Thanks mate!!

**Comment by dougludlow** [comment]
:thumbsup:
